import { clientError } from './http.js';
export const PROMO_RE=/^[A-Z0-9][A-Z0-9_-]{2,39}$/;
export function normalisePromoCode(value){const code=typeof value==='string'?value.trim().toUpperCase():'';if(!PROMO_RE.test(code))throw clientError('Provide a valid promo code.');return code;}
const ms=v=>v?.toMillis?v.toMillis():new Date(v).getTime();
export function calculatePromoDiscount(promo,lines,subtotal,now=new Date()){
 if(!promo.active)throw clientError('This promo code is inactive.',409); const time=now instanceof Date?now.getTime():new Date(now).getTime();
 if(Number.isFinite(ms(promo.startsAt))&&time<ms(promo.startsAt))throw clientError('This promo code is not active yet.',409);
 if(Number.isFinite(ms(promo.endsAt))&&time>ms(promo.endsAt))throw clientError('This promo code has expired.',409);
 if(subtotal<Number(promo.minimumOrderValue||0))throw clientError('This promo code requires a higher order value.',409);
 const p=Array.isArray(promo.productIds)?promo.productIds:[],c=Array.isArray(promo.categoryIds)?promo.categoryIds:[];
 const eligible=lines.filter(l=>(!p.length&&!c.length)||p.includes(l.productId)||c.includes(l.categoryId));const eligibleSubtotal=eligible.reduce((n,l)=>n+(Number(l.lineTotal)||0),0);
 if(!eligibleSubtotal)throw clientError('This promo code does not apply to the selected products.',409);
 const discount=promo.discountType==='PERCENTAGE'?Math.floor(eligibleSubtotal*Number(promo.discountValue)/100):Math.min(Number(promo.discountValue),eligibleSubtotal);
 return {discount,eligibleSubtotal,eligible};
}
export function validatePromotion(input,{partial=false}={}){const allowed=['code','name','description','active','startsAt','endsAt','discountType','discountValue','productIds','categoryIds','minimumOrderValue','maximumUsage','perCustomerUsage'];for(const k of Object.keys(input||{}))if(!allowed.includes(k))throw clientError(`Unknown promotion field: ${k}.`);const p={...input};if(!partial||'code'in p)p.code=normalisePromoCode(p.code);if(!partial||'name'in p){if(typeof p.name!=='string'||p.name.trim().length<3||p.name.trim().length>120)throw clientError('Name must be 3 to 120 characters.');p.name=p.name.trim();}for(const k of ['productIds','categoryIds']){if(!partial||k in p){if(!Array.isArray(p[k])||p[k].length>100||p[k].some(x=>typeof x!=='string'||!/^[A-Za-z0-9_-]{1,100}$/.test(x)))throw clientError(`${k} must contain at most 100 valid ids.`);p[k]=[...new Set(p[k])];}}if(!partial||'discountType'in p){if(!['PERCENTAGE','FIXED'].includes(p.discountType))throw clientError('Provide a valid discount type.');}for(const k of ['discountValue','minimumOrderValue','perCustomerUsage'])if(!partial||k in p){if(!Number.isInteger(p[k])||p[k]<(k==='perCustomerUsage'?1:0)||(k==='discountValue'&&p[k]<1)||(k==='perCustomerUsage'&&p[k]>100))throw clientError(`Provide a valid ${k}.`);}if(p.discountType==='PERCENTAGE'&&p.discountValue>100)throw clientError('Percentage discount cannot exceed 100.');if(p.maximumUsage!=null&&(!Number.isInteger(p.maximumUsage)||p.maximumUsage<1))throw clientError('Provide a valid maximumUsage.');if(!partial||'active'in p){if(typeof p.active!=='boolean')throw clientError('active must be true or false.');}if(!partial||'startsAt'in p||'endsAt'in p){if(!Number.isFinite(ms(p.startsAt))||!Number.isFinite(ms(p.endsAt))||ms(p.endsAt)<=ms(p.startsAt))throw clientError('End date must be after start date.');}return p;}
