import React,{useState,useEffect} from 'react';
import {Link} from 'react-router-dom';
import {ArrowLeft,Sparkles,Upload,Trash2,AlertTriangle,CheckCircle2,Loader2} from 'lucide-react';
import {apiFetch} from '../lib/api';
import {Card,Button} from '../components/ui';
const CATS=['Block Heels','Flats','Heels','Loafers','Platforms','Sandals','Slides'];
const SIZES=Array.from({length:16},(_,i)=>String(i+30));
type Row={key:string;file:File;preview:string;image?:any;name:string;description:string;price:string;size:string;category:string;pc:string;sc:string;state:'waiting'|'working'|'ready'|'error';error?:string};
const imageFile=(f:File)=>/^image\/(jpeg|png|webp)$/.test(f.type)||/\.(jpe?g|png|webp)$/i.test(f.name);
export default function AdminBulkShoeUpload(){
 const [rows,setRows]=useState<Row[]>([]),[cats,setCats]=useState<any[]>([]),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{apiFetch('/api/categories').then((v:any)=>setCats(Array.isArray(v)?v:v?.categories||[])).catch(()=>setCats([]))},[]);
 const add=(files:FileList|File[])=>{const selected=Array.from(files).filter(imageFile);if(!selected.length){setMsg('Choose JPG, PNG, or WEBP images. Extract ZIP files first, then select the folder.');return}setRows(old=>[...old,...selected.map(file=>({key:`${file.name}-${file.size}-${file.lastModified}-${Math.random()}`,file,preview:URL.createObjectURL(file),name:'',description:'',price:'',size:'',category:'Sandals',pc:'low',sc:'low',state:'waiting' as const}))]);setMsg('')};
 async function process(row:Row){try{const s:any=await apiFetch('/api/media/sign-upload',{method:'POST',body:JSON.stringify({resourceType:'image',fileName:row.file.name,bytes:row.file.size,purpose:'products'})});const fd=new FormData();fd.append('file',row.file);fd.append('api_key',s.apiKey);fd.append('timestamp',String(s.timestamp));fd.append('signature',s.signature);fd.append('folder',s.folder);fd.append('public_id',s.publicId);fd.append('allowed_formats',s.allowedFormats.join(','));const up=await fetch(`https://api.cloudinary.com/v1_1/${s.cloudName}/image/upload`,{method:'POST',body:fd});const u:any=await up.json();if(!up.ok||!u.secure_url)throw Error(u.error?.message||'Image upload failed');const img={url:u.secure_url,publicId:u.public_id,resourceType:'image'};const a:any=await apiFetch('/api/admin?route=bulk-shoes/analyze',{method:'POST',body:JSON.stringify({imageUrl:img.url})});return {image:img,name:a.name||row.file.name.replace(/\.[^.]+$/,''),description:a.description||'',price:a.price==null?'':String(a.price),size:a.size||'',category:a.category||'Sandals',pc:a.priceConfidence||'low',sc:a.sizeConfidence||'low',state:'ready' as const}}catch(e:any){return {state:'error' as const,error:e?.message||'Analysis failed'}}}
 const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
 async function analyse(){if(busy)return;setBusy(true);const queue=rows.filter(x=>x.state==='waiting'||x.state==='error');try{for(let i=0;i<queue.length;i++){const r=queue[i];if(i>0){setMsg(`Rate-limit protection: waiting before analysing ${i+1} of ${queue.length}…`);await wait(22000)}setRows(old=>old.map(x=>x.key===r.key?{...x,state:'working',error:undefined}:x));const out=await process(r);setRows(old=>old.map(x=>x.key===r.key?{...x,...out}:x))}}finally{setBusy(false);setMsg('Analysis finished. Review flagged prices and sizes before saving drafts.')}}
 const edit=(key:string,field:string,value:string)=>setRows(old=>old.map(r=>r.key===key?{...r,[field]:value}:r));
 async function save(){const list=rows.filter(r=>r.state==='ready');if(!list.length)return;for(const r of list){if(!r.name.trim()||!r.description.trim()||!/^\d+$/.test(r.price)||!SIZES.includes(r.size)||!r.image){setMsg(`Complete name, description, price and one confirmed size for ${r.file.name} before saving.`);return}if(!cats.find(c=>c.name.toLowerCase()===r.category.toLowerCase())){setMsg(`Category "${r.category}" is missing in your existing category list.`);return}}setSaving(true);let n=0;try{for(const r of list){const categoryId=cats.find(c=>c.name.toLowerCase()===r.category.toLowerCase()).id;await apiFetch('/api/admin/products',{method:'POST',body:JSON.stringify({name:r.name.trim(),description:r.description.trim(),categoryId,sku:`HS-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`,price:Number(r.price),salePrice:null,inventory:[{size:r.size,quantity:0}],images:[r.image],video:null,status:'DRAFT',featured:false,bestseller:false,newArrival:false})});n++}setRows(old=>old.filter(r=>!list.some(x=>x.key===r.key)));setMsg(`Saved ${n} unpublished product draft(s). Add inventory and publish them from Products when ready.`)}catch(e:any){setMsg(`Saved ${n} draft(s); remaining products are still here. ${e?.message||''}`)}finally{setSaving(false)}}
 const ready=rows.filter(r=>r.state==='ready').length;
 return <div className="space-y-6 animate-fadeIn"><div><Link to="/admin" className="inline-flex items-center text-sm text-neutral-500 mb-2"><ArrowLeft className="w-4 h-4 mr-1"/>Admin dashboard</Link><h1 className="text-2xl font-bold text-neutral-900">AI Bulk Shoe Uploader</h1><p className="text-sm text-neutral-500 mt-1">Upload many real product photos. AI analyses them one at a time with rate-limit protection; review every field, then save as unpublished drafts.</p></div>
 <Card className="p-5 space-y-4"><div className="flex items-center gap-3"><Sparkles className="w-6 h-6"/><div><h2 className="font-semibold">1. Choose product photos</h2><p className="text-sm text-neutral-500">Photos open first so you can pick images directly. Use the separate folder option if your shoes are organised into folders. Original photos are preserved.</p></div></div>
 <div className="grid sm:grid-cols-2 gap-3">
 <label className="block rounded-xl border-2 border-dashed border-neutral-300 p-6 text-center cursor-pointer hover:bg-neutral-50"><Upload className="w-8 h-8 mx-auto mb-2 text-neutral-400"/><span className="font-medium">Choose images</span><p className="text-xs text-neutral-500 mt-1">Open photos first · select multiple</p><input type="file" multiple accept="image/*,.jpg,.jpeg,.png,.webp" className="hidden" onChange={e=>{if(e.target.files)add(e.target.files);e.currentTarget.value=''}}/></label>
 <label className="block rounded-xl border-2 border-dashed border-neutral-300 p-6 text-center cursor-pointer hover:bg-neutral-50"><Upload className="w-8 h-8 mx-auto mb-2 text-neutral-400"/><span className="font-medium">Choose a folder</span><p className="text-xs text-neutral-500 mt-1">Browse folders of JPG, PNG, WEBP</p><input type="file" multiple accept="image/jpeg,image/png,image/webp" className="hidden" {...({webkitdirectory:'',directory:''} as any)} onChange={e=>{if(e.target.files)add(e.target.files);e.currentTarget.value=''}}/></label>
 </div>
 <div className="flex flex-wrap gap-3 items-center"><Button onClick={analyse} disabled={busy||!rows.some(r=>r.state==='waiting'||r.state==='error')}>{busy?<><Loader2 className="w-4 h-4 mr-2 animate-spin"/>Analysing…</>:<><Sparkles className="w-4 h-4 mr-2"/>Upload & analyse</>}</Button><span className="text-sm text-neutral-500">{rows.length} selected · {ready} analysed</span></div>
 {msg&&<p role="status" className="rounded-lg bg-neutral-50 border p-3 text-sm">{msg}</p>}</Card>
 {rows.length>0&&<Card className="p-5 space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">2. Review and edit</h2><p className="text-sm text-neutral-500">Unclear prices/sizes are flagged, not guessed.</p></div><Button onClick={save} disabled={saving||!ready}>{saving?'Saving…':`Save ${ready} drafts`}</Button></div>
 <div className="space-y-4">{rows.map((r,i)=>{const flagged=!r.price||!r.size||r.pc!=='high'||r.sc!=='high';return <div key={r.key} className="border rounded-xl p-4 flex gap-3"><img src={r.image?.url||r.preview} alt="" className="w-24 h-24 rounded-lg object-cover bg-neutral-100"/><div className="flex-1 min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="text-sm">Product {i+1}: {r.file.name}</strong>{r.state==='working'&&<span className="text-xs">Uploading / reading…</span>}{r.state==='error'&&<span className="text-xs text-red-600">{r.error}</span>}{r.state==='ready'&&(flagged?<span className="text-xs text-amber-800"><AlertTriangle className="inline w-3 h-3"/> Needs review</span>:<span className="text-xs text-emerald-700"><CheckCircle2 className="inline w-3 h-3"/> AI read</span>)}</div>
 {r.state==='ready'&&<div className="grid sm:grid-cols-2 gap-3 mt-3"><label className="text-xs">Name<input className="mt-1 w-full border rounded-lg p-2 text-sm" value={r.name} onChange={e=>edit(r.key,'name',e.target.value)}/></label><label className="text-xs">Price (KSh)<input type="number" min="0" step="1" className="mt-1 w-full border rounded-lg p-2 text-sm" value={r.price} onChange={e=>edit(r.key,'price',e.target.value)}/></label><label className="text-xs">Size printed on photo<select className="mt-1 w-full border rounded-lg p-2 text-sm" value={r.size} onChange={e=>edit(r.key,'size',e.target.value)}><option value="">Confirm size</option>{SIZES.map(s=><option key={s}>{s}</option>)}</select></label><label className="text-xs">Category<select className="mt-1 w-full border rounded-lg p-2 text-sm" value={r.category} onChange={e=>edit(r.key,'category',e.target.value)}>{CATS.map(c=><option key={c}>{c}</option>)}</select></label><label className="text-xs sm:col-span-2">Description<textarea rows={2} maxLength={4000} className="mt-1 w-full border rounded-lg p-2 text-sm" value={r.description} onChange={e=>edit(r.key,'description',e.target.value)}/></label></div>}
 {r.state==='ready'&&flagged&&<p className="text-xs text-amber-800 mt-2">Please verify price and size from the photo before saving.</p>}</div><button onClick={()=>{URL.revokeObjectURL(r.preview);setRows(old=>old.filter(x=>x.key!==r.key))}} aria-label="Remove" className="p-2 text-neutral-400 hover:text-red-600"><Trash2 className="w-4 h-4"/></button></div>})}</div></Card>}</div>
}