import React,{useState,useEffect} from 'react';
import {Link} from 'react-router-dom';
import {ArrowLeft,Sparkles,Upload,Trash2,AlertTriangle,CheckCircle2,Loader2,RefreshCw,PackageCheck} from 'lucide-react';
import {apiFetch} from '../lib/api';
import {Card,Button} from '../components/ui';

const CATS=['Block Heels','Flats','Heels','Loafers','Platforms','Sandals','Slides'];
const SIZES=Array.from({length:16},(_,i)=>String(i+30));
const STORAGE_KEY='herstepp-bulk-shoe-uploader-v2';
type Row={key:string;file:File;fileName:string;preview:string;image?:any;name:string;description:string;price:string;size:string;category:string;pc:string;sc:string;quantity:string;newArrival:boolean;featured:boolean;bestseller:boolean;state:'waiting'|'working'|'ready'|'error';error?:string};
type SavedRow=Omit<Row,'file'|'preview'|'state'> & {state?:string};
const imageFile=(f:File)=>/^image\/(jpeg|png|webp)$/.test(f.type)||/\.(jpe?g|png|webp)$/i.test(f.name);
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));

export default function AdminBulkShoeUpload(){
 const [rows,setRows]=useState<Row[]>([]),[cats,setCats]=useState<any[]>([]),[busy,setBusy]=useState(false),[publishing,setPublishing]=useState(false),[msg,setMsg]=useState('');
 useEffect(()=>{apiFetch('/api/categories').then((v:any)=>setCats(Array.isArray(v)?v:v?.categories||[])).catch(()=>setCats([]))},[]);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw){const saved:SavedRow[]=JSON.parse(raw);setRows(saved.map(s=>({...s,file:new File([],s.fileName||'shoe-image.jpg',{type:'image/jpeg'}),preview:s.image?.url||'',state:s.state==='ready'||s.state==='error'?'ready'==='error'?'error':s.state as Row['state']:'error',error:s.error||'Restored from this device. Retry analysis if needed.'} as Row)))}}catch{setMsg('Could not restore the previous upload list on this device.')}},[]);
 useEffect(()=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(rows.map(({file,preview,...r})=>({...r,fileName:r.fileName,preview:undefined}))))}catch{setMsg('Your browser storage is full. Publish or remove items to continue.')}},[rows]);
 const add=(files:FileList|File[])=>{const selected=Array.from(files).filter(imageFile);if(!selected.length){setMsg('Choose JPG, PNG, or WEBP images. Extract ZIP files first, then select the folder.');return}setRows(old=>[...old,...selected.map(file=>({key:`${file.name}-${file.size}-${file.lastModified}-${Math.random()}`,file,fileName:file.name,preview:URL.createObjectURL(file),name:'',description:'',price:'',size:'',category:'Sandals',pc:'low',sc:'low',quantity:'5',newArrival:true,featured:false,bestseller:false,state:'waiting' as const}))]);setMsg('')};
 async function uploadOriginal(row:Row){const s:any=await apiFetch('/api/media/sign-upload',{method:'POST',body:JSON.stringify({resourceType:'image',fileName:row.fileName,bytes:row.file.size,purpose:'products'})});const fd=new FormData();fd.append('file',row.file);fd.append('api_key',s.apiKey);fd.append('timestamp',String(s.timestamp));fd.append('signature',s.signature);fd.append('folder',s.folder);fd.append('public_id',s.publicId);fd.append('allowed_formats',s.allowedFormats.join(','));const up=await fetch(`https://api.cloudinary.com/v1_1/${s.cloudName}/image/upload`,{method:'POST',body:fd});const u:any=await up.json();if(!up.ok||!u.secure_url)throw Error(u.error?.message||'Image upload failed');return {url:u.secure_url,publicId:u.public_id,resourceType:'image'};}
 async function process(row:Row,onImage:(image:any)=>void){let image=row.image;try{if(!image){image=await uploadOriginal(row);onImage(image)}const a:any=await apiFetch('/api/admin?route=bulk-shoes/analyze',{method:'POST',body:JSON.stringify({imageUrl:image.url})});return {image,name:a.name||row.fileName.replace(/\.[^.]+$/,''),description:a.description||'',price:a.price==null?'':String(a.price),size:a.size||'',category:a.category||'Sandals',pc:a.priceConfidence||'low',sc:a.sizeConfidence||'low',state:'ready' as const,error:undefined}}catch(e:any){return {image,state:'error' as const,error:e?.message||'Analysis failed. Tap retry to try again.'}}}
 async function analyse(keys?:string[]){if(busy)return;setBusy(true);const queue=rows.filter(x=>(!keys||keys.includes(x.key))&&(x.state==='waiting'||x.state==='error'));try{for(let i=0;i<queue.length;i++){const r=queue[i];if(i>0){setMsg(`Rate-limit protection: waiting before analysing ${i+1} of ${queue.length}…`);await wait(22000)}setRows(old=>old.map(x=>x.key===r.key?{...x,state:'working',error:undefined}:x));const out=await process(r,image=>setRows(old=>old.map(x=>x.key===r.key?{...x,image}:x)));setRows(old=>old.map(x=>x.key===r.key?{...x,...out}:x))}}finally{setBusy(false);setMsg('Analysis finished. Failed images remain here; retry them when ready. Review any flagged details before publishing.')}} 
 const edit=(key:string,field:string,value:string|boolean)=>setRows(old=>old.map(r=>r.key===key?{...r,[field]:value}:r));
 async function publish(){const list=rows.filter(r=>r.state==='ready');if(!list.length)return;for(const r of list){if(!r.name.trim()||!r.description.trim()||!/^\d+$/.test(r.price)||!SIZES.includes(r.size)||!r.image){setMsg(`Complete name, description, price and confirmed size for ${r.fileName} before publishing.`);return}if(!/^\d+$/.test(r.quantity)||Number(r.quantity)<5){setMsg(`Stock for ${r.fileName} must be at least 5 pairs for its selected size.`);return}if(!cats.find(c=>c.name.toLowerCase()===r.category.toLowerCase())){setMsg(`Category "${r.category}" is missing in your existing category list.`);return}}
 setPublishing(true);let n=0;const done:string[]=[];try{for(const r of list){const categoryId=cats.find(c=>c.name.toLowerCase()===r.category.toLowerCase()).id;await apiFetch('/api/admin/products',{method:'POST',body:JSON.stringify({name:r.name.trim(),description:r.description.trim(),categoryId,sku:`HS-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,7).toUpperCase()}`,price:Number(r.price),salePrice:null,inventory:[{size:r.size,quantity:Number(r.quantity)}],images:[r.image],video:null,status:'ACTIVE',featured:r.featured,bestseller:r.bestseller,newArrival:r.newArrival})});n++;done.push(r.key)}setRows(old=>old.filter(r=>!done.includes(r.key)));setMsg(`Published ${n} product(s) to your live shop. Failed analysis items are still saved in this uploader.`)}catch(e:any){setRows(old=>old.filter(r=>!done.includes(r.key)));setMsg(`Published ${n} product(s); the remaining analysed items are still here. ${e?.message||''}`)}finally{setPublishing(false)}}
 const ready=rows.filter(r=>r.state==='ready').length,failed=rows.filter(r=>r.state==='error').length;
 return <div className="space-y-6 animate-fadeIn"><div><Link to="/admin" className="inline-flex items-center text-sm text-neutral-500 mb-2"><ArrowLeft className="w-4 h-4 mr-1"/>Admin dashboard</Link><h1 className="text-2xl font-bold text-neutral-900">AI Bulk Shoe Uploader</h1><p className="text-sm text-neutral-500 mt-1">Upload images or a folder, let AI analyse them, then publish all successful products together. Failed images stay saved on this device for retry.</p></div>
 <Card className="p-5 space-y-4"><div className="flex items-center gap-3"><Sparkles className="w-6 h-6"/><div><h2 className="font-semibold">1. Choose product photos</h2><p className="text-sm text-neutral-500">Original photos are preserved. AI reads the visible price and size and suggests product details.</p></div></div>
 <div className="grid sm:grid-cols-2 gap-3"><label className="block rounded-xl border-2 border-dashed border-neutral-300 p-6 text-center cursor-pointer hover:bg-neutral-50"><Upload className="w-8 h-8 mx-auto mb-2 text-neutral-400"/><span className="font-medium">Choose images</span><p className="text-xs text-neutral-500 mt-1">Select multiple photos</p><input type="file" multiple accept="image/*,.jpg,.jpeg,.png,.webp" className="hidden" onChange={e=>{if(e.target.files)add(e.target.files);e.currentTarget.value=''}}/></label><label className="block rounded-xl border-2 border-dashed border-neutral-300 p-6 text-center cursor-pointer hover:bg-neutral-50"><Upload className="w-8 h-8 mx-auto mb-2 text-neutral-400"/><span className="font-medium">Choose a folder</span><p className="text-xs text-neutral-500 mt-1">Browse folders of JPG, PNG, WEBP</p><input type="file" multiple accept="image/jpeg,image/png,image/webp" className="hidden" {...({webkitdirectory:'',directory:''} as any)} onChange={e=>{if(e.target.files)add(e.target.files);e.currentTarget.value=''}}/></label></div>
 <div className="flex flex-wrap gap-3 items-center"><Button onClick={()=>analyse()} disabled={busy||!rows.some(r=>r.state==='waiting'||r.state==='error')}>{busy?<><Loader2 className="w-4 h-4 mr-2 animate-spin"/>Analysing…</>:<><Sparkles className="w-4 h-4 mr-2"/>Analyse / retry failed</>}</Button><span className="text-sm text-neutral-500">{rows.length} saved · {ready} ready to publish · {failed} failed</span></div>{msg&&<p role="status" className="rounded-lg bg-neutral-50 border p-3 text-sm">{msg}</p>}</Card>
 {rows.length>0&&<Card className="p-5 space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">2. Review and publish</h2><p className="text-sm text-neutral-500">Select a stock quantity of at least 5 pairs. Products are published directly and become visible in the shop.</p></div><Button onClick={publish} disabled={publishing||!ready}>{publishing?<><Loader2 className="w-4 h-4 mr-2 animate-spin"/>Publishing…</>:<><PackageCheck className="w-4 h-4 mr-2"/>Publish {ready} products</>}</Button></div>
 <div className="space-y-4">{rows.map((r,i)=>{const flagged=!r.price||!r.size||r.pc!=='high'||r.sc!=='high';return <div key={r.key} className="border rounded-xl p-4 flex gap-3"><img src={r.image?.url||r.preview} alt="" className="w-24 h-24 rounded-lg object-cover bg-neutral-100"/><div className="flex-1 min-w-0"><div className="flex flex-wrap items-center gap-2"><strong className="text-sm">Product {i+1}: {r.fileName}</strong>{r.state==='working'&&<span className="text-xs">Uploading / reading…</span>}{r.state==='error'&&<span className="text-xs text-red-600">{r.error||'Analysis failed'}</span>}{r.state==='ready'&&(flagged?<span className="text-xs text-amber-800"><AlertTriangle className="inline w-3 h-3"/> Needs review</span>:<span className="text-xs text-emerald-700"><CheckCircle2 className="inline w-3 h-3"/> AI read</span>)}</div>
 {r.state==='error'&&<div className="flex flex-wrap gap-2 mt-3"><Button onClick={()=>analyse([r.key])} disabled={busy}><RefreshCw className="w-4 h-4 mr-1"/>Retry analysis</Button>{!r.image&&<span className="text-xs text-neutral-500 self-center">If upload failed, reselect this image after removing it.</span>}</div>}
 {r.state==='ready'&&<div className="grid sm:grid-cols-2 gap-3 mt-3"><label className="text-xs">Name<input className="mt-1 w-full border rounded-lg p-2 text-sm" value={r.name} onChange={e=>edit(r.key,'name',e.target.value)}/></label><label className="text-xs">Price (KSh)<input type="number" min="0" step="1" className="mt-1 w-full border rounded-lg p-2 text-sm" value={r.price} onChange={e=>edit(r.key,'price',e.target.value)}/></label><label className="text-xs">Size printed on photo<select className="mt-1 w-full border rounded-lg p-2 text-sm" value={r.size} onChange={e=>edit(r.key,'size',e.target.value)}><option value="">Confirm size</option>{SIZES.map(s=><option key={s}>{s}</option>)}</select></label><label className="text-xs">Category<select className="mt-1 w-full border rounded-lg p-2 text-sm" value={r.category} onChange={e=>edit(r.key,'category',e.target.value)}>{CATS.map(c=><option key={c}>{c}</option>)}</select></label><label className="text-xs">Stock quantity (minimum 5)<input type="number" min="5" step="1" className="mt-1 w-full border rounded-lg p-2 text-sm" value={r.quantity} onChange={e=>edit(r.key,'quantity',e.target.value)}/></label><label className="text-xs sm:col-span-2">Description<textarea rows={2} maxLength={4000} className="mt-1 w-full border rounded-lg p-2 text-sm" value={r.description} onChange={e=>edit(r.key,'description',e.target.value)}/></label><div className="sm:col-span-2 flex flex-wrap gap-x-5 gap-y-2 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={r.newArrival} onChange={e=>edit(r.key,'newArrival',e.target.checked)}/> Mark as New</label><label className="flex items-center gap-2"><input type="checkbox" checked={r.featured} onChange={e=>edit(r.key,'featured',e.target.checked)}/> Featured</label><label className="flex items-center gap-2"><input type="checkbox" checked={r.bestseller} onChange={e=>edit(r.key,'bestseller',e.target.checked)}/> Bestseller</label></div></div>}{r.state==='ready'&&flagged&&<p className="text-xs text-amber-800 mt-2">Please verify price and size from the photo before publishing.</p>}</div><button onClick={()=>{if(r.preview.startsWith('blob:'))URL.revokeObjectURL(r.preview);setRows(old=>old.filter(x=>x.key!==r.key))}} aria-label="Remove" className="p-2 text-neutral-400 hover:text-red-600"><Trash2 className="w-4 h-4"/></button></div>})}</div></Card>}</div>
}
